# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: speziclaid_datatypes.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class SleepSample(betterproto.Message):
    value: int = betterproto.int32_field(1)
    timestamp: int = betterproto.uint64_field(2)


@dataclass(eq=False, repr=False)
class SleepData(betterproto.Message):
    sleep_samples: "SleepSample" = betterproto.message_field(1)
